@id=ad2edaa9-ecab-4aa3-9169-bfc82d543605

PUT http://localhost:5299/breakfasts/{{id}}
Content-Type: application / json

{
    "name": "Bacon and eggs3 bro",
    "description": "Bacon and eggs with toast",
    "startDateTime": "2017-01-01T08:00:00",
    "endDateTime": "2017-01-01T09:00:00",
    "savory":[
        "bacon",
        "eggs",
        "toast"
    ],
    "Sweet":[
        "jammm",
        "butter"
    ]
}
